language: vim

before_script:
  - sudo add-apt-repository ppa:jonathonf/vim -y
  - sudo apt-get update
  - sudo apt-get install vim -y
  - git clone https://github.com/junegunn/vader.vim.git ../vader.vim

script: ./ci.sh
